apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-predictor
  labels:
    app: diabetes-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetes-predictor
  template:
    metadata:
      labels:
        app: diabetes-predictor
    spec:
      containers:
        - name: diabetes-api
          #
          # ---------------------------------------------------------------
          # !!! IMPORTANT !!!
          # Change this image path to your own Docker Hub/GCR/ECR repository
          # e.g., your-dockerhub-username/mlops-diabetes-predictor:latest
          # ---------------------------------------------------------------
          #
          image: your-dockerhub-username/mlops-diabetes-predictor:latest
          ports:
            - containerPort: 8000
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-predictor-service
spec:
  selector:
    app: diabetes-predictor
  ports:
    - protocol: TCP
      port: 80       # Expose the service on port 80 (standard HTTP)
      targetPort: 8000 # Forward traffic to the container's port 8000
  type: LoadBalancer